name: Build and Deploy train-ticket-reservation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout code
        uses: actions/checkout@v4

      - name: â˜• Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: ðŸ”¨ Build with Maven
        run: mvn clean package -DskipTests

      - name: â¬† Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-file
          path: target/*.war

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ Download WAR
        uses: actions/download-artifact@v4
        with:
          name: war-file
          path: .

      - name: ðŸš€ Deploy to DEV
        env:
          URL: ${{ secrets.TOMCAT_URL_DEV }}
          USER: ${{ secrets.TOMCAT_USER_DEV }}
          PASS: ${{ secrets.TOMCAT_PASS_DEV }}
        run: |
          WAR_FILE=$(ls *.war)
          echo "Deploying $WAR_FILE to DEV"

          curl -u "$USER:$PASS" "$URL/list"

          curl -u "$USER:$PASS" --fail -T "$WAR_FILE" \
          "$URL/deploy?path=/train-ticket-reservation&update=true"

  deploy-test:
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file
          path: .

      - name: ðŸš€ Deploy to TEST
        env:
          URL: ${{ secrets.TOMCAT_URL_TEST }}
          USER: ${{ secrets.TOMCAT_USER_TEST }}
          PASS: ${{ secrets.TOMCAT_PASS_TEST }}
        run: |
          WAR_FILE=$(ls *.war)
          curl -u "$USER:$PASS" -T "$WAR_FILE" \
          "$URL/deploy?path=/train-ticket-reservation&update=true"

  deploy-pre-prod:
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file
          path: .

      - name: ðŸš€ Deploy to PRE-PROD
        env:
          URL: ${{ secrets.TOMCAT_URL_PRE_PROD }}
          USER: ${{ secrets.TOMCAT_USER_PRE_PROD }}
          PASS: ${{ secrets.TOMCAT_PASS_PRE_PROD }}
        run: |
          WAR_FILE=$(ls *.war)
          curl -u "$USER:$PASS" -T "$WAR_FILE" \
          "$URL/deploy?path=/train-ticket-reservation&update=true"

  deploy-prod:
    needs: deploy-pre-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: war-file
          path: .

      - name: ðŸš€ Deploy to PROD
        env:
          URL: ${{ secrets.TOMCAT_URL_PROD }}
          USER: ${{ secrets.TOMCAT_USER_PROD }}
          PASS: ${{ secrets.TOMCAT_PASS_PROD }}
        run: |
          WAR_FILE=$(ls *.war)
          curl -u "$USER:$PASS" -T "$WAR_FILE" \
          "$URL/deploy?path=/train-ticket-reservation&update=true"
